
const DATA_URL = "../data/market-data.json";
let payload = null;
let candidates = [];

const $ = selector => document.querySelector(selector);
const fmt = (value, digits=2) => Number.isFinite(Number(value))
  ? Number(value).toLocaleString("it-IT",{minimumFractionDigits:digits,maximumFractionDigits:digits})
  : "—";

function statusIcon(status){return status==="GREEN"?"✓":status==="YELLOW"?"!":"✕"}
function confirmed(item){return Boolean(item?.confirmation?.confirmed)}
function confirmationDays(item){return Number(item?.confirmation?.days ?? 0)}
function requiredDays(item){return Number(item?.confirmation?.requiredDays ?? payload?.rules?.entryConfirmationDays ?? 5)}

function conviction(item){
  const score=Number(item?.stableScore??item?.finalScore??0),confidence=Number(item?.memory?.confidencePct??0),entry=Number(item?.entryScore??0);
  if(!confirmed(item)) return {stars:Math.min(3,Math.max(1,Math.round(score/2.5))),starsText:"★".repeat(Math.min(3,Math.max(1,Math.round(score/2.5))))+"☆".repeat(5-Math.min(3,Math.max(1,Math.round(score/2.5)))),text:`IN CONFERMA ${confirmationDays(item)}/${requiredDays(item)} GIORNI`,detail:"Non è ancora un via libera all'acquisto"};
  if(score>=8.3&&confidence>=75&&entry>=7.2)return{stars:5,starsText:"★★★★★",text:"ACQUISTO CONFERMATO",detail:"Setup persistente: ingresso pianificabile nella zona indicata"};
  if(score>=7.7&&entry>=6.2)return{stars:4,starsText:"★★★★☆",text:"ACQUISTO CONFERMATO",detail:"Condizioni confermate per più giorni di Borsa"};
  return{stars:3,starsText:"★★★☆☆",text:"CANDIDATA CONFERMATA",detail:"Valutare il prezzo prima dell'ingresso"};
}

function greenReadiness(item){
  const missing=[],passed=[],entry=Number(item?.entryScore??0),trend=Number(item?.trendScore??0),quality=Number(item?.qualityScore??0),news=Number(item?.newsScore??0),pullback=pullbackAssessment(item);
  if(pullback.level==="IDEAL"||pullback.level==="DEEP")passed.push("Prezzo in area utile");else missing.push("Prezzo non ancora nella zona ideale");
  if(entry>=7)passed.push(`Ingresso ${fmt(entry,1)}/10`);else missing.push(`Ingresso ${fmt(entry,1)}/10: serve almeno 7/10`);
  if(trend>=6.5)passed.push(`Trend ${fmt(trend,1)}/10`);else missing.push(`Trend ${fmt(trend,1)}/10: serve maggiore conferma`);
  if(quality>=6.5)passed.push(`Qualità ${fmt(quality,1)}/10`);else missing.push(`Qualità ${fmt(quality,1)}/10: fondamentale ancora debole`);
  if(news>=5.5)passed.push(`News ${fmt(news,1)}/10`);else missing.push(`News/catalizzatori ${fmt(news,1)}/10: manca conferma positiva`);
  if(confirmed(item)){passed.push(`Conferma ${confirmationDays(item)}/${requiredDays(item)} giorni di Borsa`);return{state:"GREEN",title:"VERDE — ACQUISTO CONFERMATO",summary:"Il setup ha superato anche il filtro temporale. Non implica acquisto automatico: pianificare l'ingresso nella zona indicata.",missing:[],passed};}
  missing.push(`Conferma temporale ${confirmationDays(item)}/${requiredDays(item)} giorni di Borsa`);
  return{state:"YELLOW",title:`GIALLO — IN CONFERMA ${confirmationDays(item)}/${requiredDays(item)} GIORNI`,summary:"Le condizioni possono essere buone, ma il sito aspetta persistenza prima di dare il verde definitivo.",missing,passed};
}
function scoreExplanation(item){const parts=[{label:"Qualità",value:Number(item?.qualityScore??0),weight:34},{label:"Trend",value:Number(item?.trendScore??0),weight:28},{label:"Ingresso",value:Number(item?.entryScore??0),weight:25},{label:"News",value:Number(item?.newsScore??0),weight:13}],best=[...parts].sort((a,b)=>b.value-a.value)[0],worst=[...parts].sort((a,b)=>a.value-b.value)[0];return{parts,best,worst,text:`Il voto nasce soprattutto da ${best.label.toLowerCase()} (${fmt(best.value,1)}/10); il fattore più debole è ${worst.label.toLowerCase()} (${fmt(worst.value,1)}/10).`}}
function intelligenceUrl(item){return `../intelligence/?ticker=${encodeURIComponent(item.ticker||"")}#company-${encodeURIComponent(item.ticker||"")}`}
function pullbackAssessment(item){const p=Number(item?.pullbackPct??0),min=Number(item?.requiredPullbackMin??10),max=Number(item?.requiredPullbackMax??18),weekly=item?.technical?.weekly||"",quality=Number(item?.qualityScore??0);if(p<min*.55)return{level:"WAIT",label:"ANCORA POCO",detail:"Il prezzo non ha ancora corretto abbastanza."};if(p<min)return{level:"WATCH",label:"QUASI IN ZONA",detail:"Il ritracciamento si sta avvicinando alla fascia utile."};if(p<=max)return{level:"IDEAL",label:"ZONA IDEALE",detail:"Correzione coerente con la volatilità storica."};if(p<=max*1.35&&weekly!=="Ribassista"&&quality>=6)return{level:"DEEP",label:"PROFONDO MA VALIDO",detail:"Il calo è ampio, ma la struttura non risulta ancora compromessa."};return{level:"RISK",label:"CALO DA VERIFICARE",detail:"Il ribasso può indicare un problema oltre la normale correzione."}}
function statusLabel(item){if(confirmed(item))return"VERDE · ACQUISTO CONFERMATO";if(item.status==="YELLOW"||item.rawStatus==="GREEN")return`GIALLO · CONFERMA ${confirmationDays(item)}/${requiredDays(item)} GG`;return"ROSSO · ESCLUSO ORA"}
function freshness(){if(!payload?.generatedAt)return"Età dati sconosciuta";const m=Math.max(0,Math.floor((Date.now()-new Date(payload.generatedAt))/60000));return m<60?`Dati aggiornati ${m} min fa`:`Dati aggiornati ${Math.floor(m/60)}h ${m%60}m fa`}
function renderChanges(){const ch=payload?.changes||{},p=$("#changePanel");if(!p)return;p.innerHTML=`<div class="change-box"><div><small>MEMORIA DELLA CLASSIFICA</small><h3>${payload.historyDays||0} giorni osservati</h3></div><div class="change-metrics"><span><b>${ch.unchangedCount||0}</b> confermate</span><span class="entered"><b>${(ch.entered||[]).length}</b> entrate</span><span class="exited"><b>${(ch.exited||[]).length}</b> uscite</span></div><p>${(ch.entered||[]).length?`Entrano: ${(ch.entered||[]).join(", ")}.`:"Nessuna nuova entrata."} ${(ch.exited||[]).length?`Escono: ${(ch.exited||[]).join(", ")}.`:"Nessuna uscita."}</p><small>Il VERDE definitivo richiede ${payload.rules?.entryConfirmationDays||5} giorni di Borsa consecutivi con condizioni valide. La lista viene rivalutata ogni 5 giorni di Borsa, non ad ogni aggiornamento prezzi.</small></div>`}
function renderHistory(){const p=$("#historyPanel");if(!p)return;const ch=payload?.changes||{},cs=payload?.candidates||[];p.innerHTML=`<div class="history-box"><div class="history-head"><div><small>CRONOLOGIA DELLE SELEZIONI</small><h3>Chi resta, chi entra, chi esce</h3></div><div class="history-summary"><span>${cs.length} attuali</span><span>${(ch.entered||[]).length} nuove</span><span>${(ch.exited||[]).length} uscite</span></div></div><div class="history-current">${cs.map(i=>`<div class="history-row"><div><strong>${i.rank||"—"}. ${i.name}</strong><small>${i.ticker} · ${confirmed(i)?"Confermata":`In conferma ${confirmationDays(i)}/${requiredDays(i)} gg`}</small></div><div><span>Top5 ${i.memory?.consecutiveTop5Days||0} gg</span><span>Stabilità ${fmt(i.memory?.stabilityScore,1)}/10</span></div></div>`).join("")}</div><p class="history-exit">${(ch.exited||[]).length?`Uscite: ${(ch.exited||[]).join(", ")}`:"Nessuna uscita nell'ultimo aggiornamento."}</p></div>`}
function renderValidation(){const p=$("#validationPanel");if(!p)return;const s=payload?.validationSummary||{};p.innerHTML=`<div class="validation-box"><div><small>VALIDAZIONE DELLE VECCHIE SELEZIONI</small><h3>Risultati a 1, 2 e 3 mesi</h3></div><div class="validation-grid">${[20,60,90].map(d=>{const r=s[String(d)]||{};return`<div><span>${d===20?"1 mese":d===60?"2 mesi":"3 mesi"}</span><strong>${r.samples||0} casi</strong><small>${r.positivePct==null?"Storico insufficiente":`${fmt(r.positivePct,1)}% positivi · media ${fmt(r.averageReturnPct,1)}%`}</small></div>`}).join("")}</div></div>`}
function renderTop(){const ranked=[...candidates].sort((a,b)=>b.finalScore-a.finalScore).slice(0,5),lead=ranked[0];if(!lead)return;$("#topArea").innerHTML=`<div class="ranking"><small>CLASSIFICA OPERATIVA 2-4 MESI</small>${ranked.map((i,n)=>`<div class="rank-row" data-ticker="${i.ticker}"><span class="rank-num">${n+1}</span><div><strong>${i.name}</strong><small class="ticker">${i.ticker} · ${i.sector||"Settore n.d."}</small></div><div class="ranking-conviction"><span class="conviction-stars">${conviction(i).starsText}</span><strong>${conviction(i).text}</strong></div><span class="pullback-short">${fmt(i.pullbackPct,1)}% · ${pullbackAssessment(i).label}</span><span class="score">${fmt(i.finalScore,1)}/10</span></div>`).join("")}</div><aside class="lead"><small>PRIMA AZIONE DA MONITORARE</small><h3>${lead.name}</h3><span class="status ${confirmed(lead)?"GREEN":"YELLOW"}">${confirmed(lead)?"✓":"!"} ${statusLabel(lead)}</span><div class="lead-conviction"><span>${conviction(lead).starsText}</span><strong>${conviction(lead).text}</strong><small>${conviction(lead).detail}</small></div><div class="big-score">${fmt(lead.finalScore,1)}<small>/10</small></div><div class="pullback-reading ${pullbackAssessment(lead).level}"><strong>Ritracciamento ${fmt(lead.pullbackPct,1)}% · ${pullbackAssessment(lead).label}</strong><small>${pullbackAssessment(lead).detail}</small></div><p>${lead.executiveSummary}</p><strong>Zona: ${fmt(lead.entryZoneLow)}–${fmt(lead.entryZoneHigh)} ${lead.currency||""}</strong></aside>`;document.querySelectorAll(".rank-row").forEach(r=>r.addEventListener("click",()=>openDetail(r.dataset.ticker)))}
function card(i){const g=greenReadiness(i);return`<article class="card" data-ticker="${i.ticker}" data-status="${i.status}"><div class="card-head"><div><h3>${i.name}</h3><span class="ticker">${i.ticker} · ${i.sector||"—"}</span></div><div class="card-score">${fmt(i.finalScore,1)}<small>/10</small></div></div><span class="status ${confirmed(i)?"GREEN":i.status}">${confirmed(i)?"✓":i.status==="RED"?"✕":"!"} ${statusLabel(i)}</span><div class="card-conviction"><span class="conviction-stars">${conviction(i).starsText}</span><strong>${conviction(i).text}</strong><small>${conviction(i).detail}</small></div><div class="pullback-reading ${pullbackAssessment(i).level}"><strong>Ritracciamento ${fmt(i.pullbackPct,1)}% · ${pullbackAssessment(i).label}</strong><small>${pullbackAssessment(i).detail}</small></div><div class="metrics"><div class="metric"><span>Qualità azienda</span><strong>${fmt(i.qualityScore,1)}/10</strong></div><div class="metric"><span>Trend 2-4 mesi</span><strong>${fmt(i.trendScore,1)}/10</strong></div><div class="metric"><span>Ingresso</span><strong>${fmt(i.entryScore,1)}/10</strong></div><div class="metric"><span>Ritracciamento numerico</span><strong>${fmt(i.pullbackPct,1)}%</strong></div></div><div class="zones"><div class="zone"><span>Prezzo</span><strong>${fmt(i.currentPrice)} ${i.currency||""}</strong></div><div class="zone"><span>Zona ideale</span><strong>${fmt(i.entryZoneLow)}–${fmt(i.entryZoneHigh)}</strong></div><div class="zone"><span>Invalidazione</span><strong>${fmt(i.invalidation)}</strong></div><div class="zone"><span>Target medio</span><strong>${fmt(i.target2)}</strong></div></div><div class="memory-strip"><span>${confirmed(i)?"Confermata":`In conferma ${confirmationDays(i)}/${requiredDays(i)} gg`}</span><span>Top5: ${i.memory?.consecutiveTop5Days||0} gg</span><span>Stabilità ${fmt(i.memory?.stabilityScore,1)}/10</span><span>Fiducia ${fmt(i.memory?.confidencePct,0)}%</span></div><p class="why">${i.executiveSummary}</p><div class="green-readiness ${g.state}"><strong>${g.title}</strong><span>${g.summary}</span>${g.missing.length?`<ul>${g.missing.map(x=>`<li>${x}</li>`).join("")}</ul>`:`<div class="all-passed">✓ Condizioni e persistenza soddisfatte</div>`}</div><div class="score-why"><strong>Perché questo voto</strong><span>${scoreExplanation(i).text}</span></div><div class="card-actions"><strong class="open">Apri report dettagliato →</strong><a class="intel-link" href="${intelligenceUrl(i)}">News, azienda e fonti →</a></div></article>`}
function renderCards(){const f=$("#statusFilter")?.value||"ALL",v=candidates.filter(i=>f==="ALL"||i.status===f).sort((a,b)=>b.finalScore-a.finalScore).slice(0,5);$("#cards").innerHTML=v.map(card).join("");document.querySelectorAll(".card").forEach(n=>n.addEventListener("click",()=>openDetail(n.dataset.ticker)))}
function openDetail(t){const i=candidates.find(x=>x.ticker===t);if(!i)return;$("#detailContent").innerHTML=`<article class="report"><small>${i.ticker} · ${i.sector||"—"} · Orizzonte 2-4 mesi</small><h2>${i.name}</h2><span class="status ${confirmed(i)?"GREEN":i.status}">${statusLabel(i)}</span><h3>Verdetto del Coach: ${fmt(i.finalScore,1)}/10</h3><p>${i.executiveSummary}</p><section class="report-section full"><h3>Conferma temporale</h3><p><strong>${confirmationDays(i)}/${requiredDays(i)} giorni di Borsa.</strong> Il verde definitivo compare soltanto dopo ${requiredDays(i)} giorni consecutivi con condizioni valide.</p></section><section class="report-section full"><h3>Piano operativo</h3><p>Zona ideale: <strong>${fmt(i.entryZoneLow)}–${fmt(i.entryZoneHigh)} ${i.currency||""}</strong> · Invalidazione: ${fmt(i.invalidation)} · Target medio: ${fmt(i.target2)}</p></section><section class="report-section full"><h3>Perché è stata selezionata</h3><p>${i.selectionReason}</p></section><p><a class="intel-link report-intel" href="${intelligenceUrl(i)}">Apri News & Catalyst Coach →</a></p></article>`;$("#detailDialog").showModal()}
async function load(){try{const r=await fetch(`${DATA_URL}?t=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw Error(`HTTP ${r.status}`);const c=await r.json();payload=c.investment||{};candidates=payload.candidates||[];$("#screenedCount").textContent=payload.screenedCount||0;$("#candidateCount").textContent=candidates.length;$("#greenCount").textContent=candidates.filter(confirmed).length;$("#yellowCount").textContent=candidates.filter(i=>!confirmed(i)&&i.status!=="RED").length;$("#freshness").textContent=freshness();renderChanges();renderHistory();renderValidation();renderTop();renderCards()}catch(e){console.error(e)}}
$("#statusFilter")?.addEventListener("change",renderCards);$("#detailClose")?.addEventListener("click",()=>$("#detailDialog").close());load();setInterval(load,300000);
