const DATA_URL="../data/market-data.json";let payload=null,candidates=[];const $=s=>document.querySelector(s);const fmt=(v,d=2)=>Number.isFinite(Number(v))?Number(v).toLocaleString("it-IT",{minimumFractionDigits:d,maximumFractionDigits:d}):"—";
function confirmed(i){return Boolean(i?.confirmation?.confirmed)}function days(i){return Number(i?.confirmation?.days??0)}function req(i){return Number(i?.confirmation?.requiredDays??payload?.rules?.entryConfirmationDays??5)}
function mtf(i){const m=i?.multiTimeframeConfirmation||{};return{monthly:Boolean(m?.monthly?.ok),weekly:Boolean(m?.weekly?.ok),daily:Boolean(m?.daily?.ok),available:Boolean(m?.monthly&&m?.weekly&&m?.daily)}}
function badText(v){const s=String(v||"").toLowerCase();return !s||s.includes("error 500")||s.includes("server error")||s.includes("that's all we know")||s.includes("there was an error")||s.includes("please try again later")}
function safeSector(i){return badText(i?.sector)?"Settore in aggiornamento":i.sector}
function exitDays(i){return Number(i?.exitConfirmation?.days??i?.weakDays??0)}
function phase(i){const t=mtf(i),temporal=days(i)>=req(i),raw=String(i?.rawStatus||i?.status||"").toUpperCase();if(confirmed(i)&&t.monthly&&t.weekly&&t.daily)return{status:"GREEN",title:"ACQUISTO CONFERMATO",detail:"5/5 + Mensile + Settimanale + Giornaliero: ingresso autorizzato dal Coach."};if(raw==="RED")return{status:"YELLOW",title:`USCITA IN OSSERVAZIONE ${Math.min(exitDays(i),5)}/5`,detail:"Il titolo non soddisfa oggi tutti i requisiti. Resta nella Top 5 finché l'uscita non è confermata secondo la regola di persistenza."};if(temporal)return{status:"YELLOW",title:"CANDIDATO 5/5 — ATTENDERE",detail:"La selezione è stabile, ma manca almeno una conferma tecnica. NON è ancora un segnale di acquisto."};return{status:"YELLOW",title:`IN CONFERMA ${days(i)}/${req(i)} GIORNI`,detail:"Deve prima completare la conferma temporale."}}
function tfLine(i){const t=mtf(i);if(!t.available)return"TF: dati tecnici in aggiornamento";const x=(ok,n)=>`${n} ${ok?"✓":"✕"}`;return`${x(t.monthly,"Mensile")} · ${x(t.weekly,"Settimanale")} · ${x(t.daily,"Giornaliero")}`}
function pullback(i){const p=Number(i?.pullbackPct||0),mn=Number(i?.requiredPullbackMin||10),mx=Number(i?.requiredPullbackMax||18);if(p<mn)return"QUASI IN ZONA";if(p<=mx)return"ZONA IDEALE";return"RITRACCIAMENTO PROFONDO"}
function entryOperational(i){const raw=Math.max(0,Math.min(10,Number(i?.entryScore||0))),t=mtf(i);if(!t.available)return raw;const ok=[t.monthly,t.weekly,t.daily].filter(Boolean).length;const cap=[4.5,6.0,7.5,10][ok];return Math.min(raw,cap)}
function intel(i){return`../intelligence/?ticker=${encodeURIComponent(i.ticker||"")}#company-${encodeURIComponent(i.ticker||"")}`}
function card(i){const p=phase(i);return`<article class="card" data-ticker="${i.ticker}" data-status="${p.status}"><div class="card-head"><div><h3>${i.name}</h3><span class="ticker">${i.ticker} · ${safeSector(i)}</span></div><div class="card-score">${fmt(i.finalScore,1)}<small>/10</small></div></div><span class="status ${p.status}">! ${p.title}</span><div class="card-conviction"><strong>${p.title}</strong><small>${p.detail}</small><small><b>${tfLine(i)}</b></small></div><div class="pullback-reading"><strong>Ritracciamento ${fmt(i.pullbackPct,1)}% · ${pullback(i)}</strong></div><div class="metrics"><div class="metric"><span>Qualità azienda</span><strong>${fmt(i.qualityScore,1)}/10</strong></div><div class="metric"><span>Trend 2-4 mesi</span><strong>${fmt(i.trendScore,1)}/10</strong></div><div class="metric"><span>Ingresso operativo</span><strong>${fmt(entryOperational(i),1)}/10</strong></div><div class="metric"><span>Ritracciamento</span><strong>${fmt(i.pullbackPct,1)}%</strong></div></div><div class="zones"><div class="zone"><span>Prezzo</span><strong>${fmt(i.currentPrice)} ${i.currency||""}</strong></div><div class="zone"><span>Zona ideale</span><strong>${fmt(i.entryZoneLow)}–${fmt(i.entryZoneHigh)}</strong></div><div class="zone"><span>Invalidazione</span><strong>${fmt(i.invalidation)}</strong></div><div class="zone"><span>Target medio</span><strong>${fmt(i.target2)}</strong></div></div><div class="memory-strip"><span>Persistenza ${days(i)}/${req(i)}</span><span>Top5: ${i.memory?.consecutiveTop5Days||0} gg</span><span>Stabilità ${fmt(i.memory?.stabilityScore,1)}/10</span><span>Fiducia ${fmt(i.memory?.confidencePct,0)}%</span></div><p class="why">${i.executiveSummary||""}</p><div class="green-readiness ${p.status}"><strong>${p.title}</strong><span>${p.detail}</span><span>${tfLine(i)}</span></div><div class="card-actions"><strong class="open">Apri report dettagliato →</strong><a class="intel-link" href="${intel(i)}">News, azienda e fonti →</a></div></article>`}
function renderCards(){const f=$("#statusFilter")?.value||"ALL",v=candidates.filter(i=>f==="ALL"||phase(i).status===f).sort((a,b)=>b.finalScore-a.finalScore).slice(0,5);$("#cards").innerHTML=v.map(card).join("");document.querySelectorAll(".card").forEach(n=>n.addEventListener("click",()=>openDetail(n.dataset.ticker)))}
function renderTop(){const r=[...candidates].sort((a,b)=>b.finalScore-a.finalScore).slice(0,5);if(!r.length)return;$("#topArea").innerHTML=`<div class="ranking"><small>CLASSIFICA 2-4 MESI · IL VERDE È SOLO OPERATIVO</small>${r.map((i,n)=>{const p=phase(i);return`<div class="rank-row" data-ticker="${i.ticker}"><span class="rank-num">${n+1}</span><div><strong>${i.name}</strong><small>${i.ticker}</small></div><div><strong>${p.title}</strong><small>${tfLine(i)}</small></div><span class="score">${fmt(i.finalScore,1)}/10</span></div>`}).join("")}</div>`;document.querySelectorAll(".rank-row").forEach(n=>n.addEventListener("click",()=>openDetail(n.dataset.ticker)))}
function openDetail(t){const i=candidates.find(x=>x.ticker===t);if(!i)return;const p=phase(i),m=mtf(i);$("#detailContent").innerHTML=`<article class="report"><small>${i.ticker} · ${safeSector(i)} · Orizzonte 2-4 mesi</small><h2>${i.name}</h2><span class="status ${p.status}">${p.title}</span><h3>Verdetto del Coach: ${fmt(i.finalScore,1)}/10</h3><p>${p.detail}</p><section class="report-section full"><h3>1. Persistenza della candidatura</h3><p><strong>${days(i)}/${req(i)} sedute.</strong> Arrivare a 5/5 significa soltanto che il titolo resta un candidato valido: non autorizza da solo l'acquisto.</p></section><section class="report-section full"><h3>2. Conferma tecnica obbligatoria</h3><p>Mensile <strong>${m.monthly?"✓ OK":"✕ ATTENDERE"}</strong> · Settimanale <strong>${m.weekly?"✓ OK":"✕ ATTENDERE"}</strong> · Giornaliero <strong>${m.daily?"✓ OK":"✕ ATTENDERE"}</strong></p><p><strong>ACQUISTO CONFERMATO</strong> compare soltanto quando sono OK 5/5 + tutti e tre i timeframe.</p></section><section class="report-section full"><h3>Piano operativo</h3><p>Zona ideale: <strong>${fmt(i.entryZoneLow)}–${fmt(i.entryZoneHigh)} ${i.currency||""}</strong> · Invalidazione: ${fmt(i.invalidation)} · Target medio: ${fmt(i.target2)}</p></section></article>`;$("#detailModal").classList.add("open");document.body.classList.add("modal-open")}
function closeDetail(){$("#detailModal")?.classList.remove("open");document.body.classList.remove("modal-open")}
function renderSummary(){const e=$("#summary");if(!e)return;const greens=candidates.filter(i=>phase(i).status==="GREEN").length,waiting=candidates.length-greens;e.innerHTML=`<div><strong>${greens}</strong><span>acquisti realmente confermati</span></div><div><strong>${waiting}</strong><span>candidati / in attesa</span></div><div><strong>${candidates.length}</strong><span>titoli monitorati</span></div>`}
async function init(){const r=await fetch(DATA_URL+"?v="+Date.now());const root=await r.json();payload=root.investment||root;candidates=payload.candidates||[];renderSummary();renderTop();renderCards();$("#statusFilter")?.addEventListener("change",renderCards);$("#closeModal")?.addEventListener("click",closeDetail);$("#detailModal")?.addEventListener("click",e=>{if(e.target.id==="detailModal")closeDetail()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeDetail()})}init();