const DATA='../data/etf-data.json';
const $=s=>document.querySelector(s);
const f=(v,d=1)=>Number.isFinite(Number(v))?Number(v).toLocaleString('it-IT',{maximumFractionDigits:d}):'—';
const euro=v=>Number(v).toLocaleString('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0});
let DATASET=[];let GENERATED_AT=null;

function role(i){const c=(i.category||'').toLowerCase(),n=(i.name||'').toLowerCase();if(c.includes('globale')&&!c.includes('obbl'))return'CORE GLOBALE';if(c.includes('usa'))return'CRESCITA USA';if(c.includes('europa'))return'DIVERSIFICAZIONE EUROPA';if(c.includes('tecnologia')||c.includes('nasdaq')||n.includes('nasdaq'))return'CRESCITA / TECNOLOGIA';if(c.includes('oro')||n.includes('gold'))return'DIFESA / ORO';if(c.includes('obbl'))return'STABILIZZATORE';return'DIVERSIFICAZIONE'}
function why(i){const r=role(i);if(r==='CORE GLOBALE')return'È il cuore del PAC: offre esposizione ampia a molte aziende e paesi in un solo strumento.';if(r==='CRESCITA USA')return'Rafforza l’esposizione alle grandi società statunitensi e il potenziale di crescita.';if(r==='DIVERSIFICAZIONE EUROPA')return'Aggiunge peso all’Europa e riduce la dipendenza esclusiva dal mercato statunitense.';if(r==='CRESCITA / TECNOLOGIA')return'Aumenta il potenziale di crescita. La sovrapposizione con il core è accettata consapevolmente ma viene segnalata.';if(r==='DIFESA / ORO')return'L’oro resta nel PAC come vera componente di diversificazione rispetto alle azioni.';if(r==='STABILIZZATORE')return'La componente obbligazionaria entra solo se competitiva: non ha più un posto garantito.';return'Completa il portafoglio con un’esposizione differente.'}
function growthScore(i){const r1=Number(i.return1y)||0,r3=Number(i.return3y)||0,r5=Number(i.return5y)||0,r10=Number(i.return10y)||0,q=(Number(i.score)||0)*10;return r1*.15+r3*.30+r5*.30+r10*.15+q*.10}
function pick5(a){const ranked=[...a].sort((x,y)=>growthScore(y)-growthScore(x)),chosen=[];const add=x=>{if(x&&!chosen.includes(x)&&chosen.length<5)chosen.push(x)};add(ranked.find(x=>role(x)==='CORE GLOBALE'));add(ranked.find(x=>role(x)==='DIVERSIFICAZIONE EUROPA'));add(ranked.find(x=>role(x)==='DIFESA / ORO'));ranked.filter(x=>!chosen.includes(x)&&role(x)!=='STABILIZZATORE').forEach(add);ranked.forEach(add);return chosen.slice(0,5)}

function containsText(i){const n=(i.name||'').toLowerCase(),r=role(i);if(n.includes('acwi'))return'Azioni di grandi e medie società dei mercati sviluppati ed emergenti di tutto il mondo. È un contenitore molto ampio: Stati Uniti pesano molto, ma include anche Europa, Giappone e mercati emergenti.';if(n.includes('stoxx europe 600'))return'Circa 600 società europee large, mid e small cap di numerosi settori. Serve a dare più peso all’Europa rispetto a un indice globale.';if(n.includes('nasdaq'))return'Le maggiori società non finanziarie quotate al Nasdaq. È molto esposto a tecnologia, comunicazioni e consumi discrezionali e quindi può essere più volatile.';if(n.includes('information technology'))return'Società del settore Information Technology dell’S&P 500: software, semiconduttori, hardware e servizi IT. È molto concentrato sulle grandi aziende tecnologiche statunitensi.';if(r==='DIFESA / ORO')return'Oro fisico detenuto a copertura del prodotto. Non contiene azioni di miniere aurifere: segue il prezzo dell’oro, al netto di costi e differenze di replica.';if(r==='CORE GLOBALE')return'Azioni globali diversificate per paesi e settori. Il numero preciso delle partecipazioni può cambiare nel tempo.';if(r==='DIVERSIFICAZIONE EUROPA')return'Azioni europee diversificate per paese e settore.';if(r==='CRESCITA / TECNOLOGIA'||r==='CRESCITA USA')return'Azioni orientate alla crescita, soprattutto statunitensi. La composizione cambia nel tempo con l’indice seguito.';return'Un paniere di strumenti coerente con l’indice o l’attività sottostante.'}
function structureText(i){const rep=(i.replication||'n.d.').toLowerCase(),dist=(i.distribution||'n.d.').toLowerCase();let s=rep.includes('fis')?'Replica fisica: il fondo acquista direttamente tutti o una parte rappresentativa dei titoli dell’indice.':'La modalità di replica va verificata nel KID/factsheet del prodotto.';s+=' ';s+=dist.includes('acc')?'Ad accumulazione: dividendi e proventi vengono reinvestiti automaticamente nel fondo.':dist.includes('dist')?'A distribuzione: i proventi vengono periodicamente pagati agli investitori.':'La politica dei proventi va verificata nel documento ufficiale.';return s}
function protectionText(i){if(role(i)==='DIFESA / ORO')return'È un ETC, non un ETF UCITS azionario. Non garantisce il capitale. Il valore dipende dall’oro e dalla struttura dell’emittente; la presenza di oro fisico a copertura riduce il rischio economico rispetto a un prodotto non collateralizzato, ma non elimina ogni rischio.';return'Un ETF UCITS non garantisce il capitale e può perdere valore. Il patrimonio del fondo è normalmente separato da quello della società di gestione e soggetto alle regole UCITS su custodia, diversificazione e trasparenza. Queste protezioni regolamentari non eliminano il rischio di mercato.'}
function riskText(i){const r=role(i);if(r==='CRESCITA / TECNOLOGIA')return'Rischio principale: forte concentrazione settoriale e nelle mega-cap USA. Può crescere più del mercato ma anche subire drawdown superiori.';if(r==='CORE GLOBALE')return'Rischio principale: mercato azionario globale e forte peso degli Stati Uniti. È diversificato, ma durante i ribassi globali può comunque perdere molto.';if(r==='DIVERSIFICAZIONE EUROPA')return'Rischio principale: ciclo economico europeo, banche, industria e valute. Diversifica geograficamente ma può sottoperformare gli USA per lunghi periodi.';if(r==='DIFESA / ORO')return'Rischio principale: prezzo dell’oro, tassi reali, dollaro e fasi di forte volatilità. Non produce utili o dividendi e può restare fermo per anni.';return'Rischio di mercato, valuta, concentrazione e tracking rispetto all’indice.'}

function quoteInfo(i){
  const raw=Number(i.currentPrice);const cur=i.quoteCurrency||'';let display='—';
  if(Number.isFinite(raw)){
    if(cur==='GBp')display=`${f(raw,2)} GBp (= £${f(raw/100,2)})`;
    else if(cur==='GBP')display=`£${f(raw,2)} GBP`;
    else if(cur==='EUR')display=`€${f(raw,2)} EUR`;
    else if(cur==='USD')display=`$${f(raw,2)} USD`;
    else display=`${f(raw,2)}${cur?' '+cur:''}`;
  }
  return {display,currency:cur||'valuta n.d.',exchange:i.exchange||((i.tvSymbol||'').startsWith('XETR:')?'Xetra':(i.tvSymbol||'').startsWith('LSE:')?'London Stock Exchange':'Mercato n.d.')};
}
function updatedLabel(){if(!GENERATED_AT)return'Aggiornamento n.d.';try{return new Intl.DateTimeFormat('it-IT',{timeZone:'Europe/Rome',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(GENERATED_AT));}catch{return GENERATED_AT}}

function chart(i){const hist=(i.monthlyHistory||[]).filter(x=>Number(x.price)>0).slice(-60);if(hist.length<2)return'<div class="price-chart empty">Storico grafico non disponibile</div>';const values=hist.map(x=>Number(x.price)),min=Math.min(...values),max=Math.max(...values),range=Math.max(1,max-min),w=700,h=220,p=18;const pts=values.map((v,n)=>`${(p+n*(w-2*p)/(values.length-1)).toFixed(1)},${(h-p-(v-min)*(h-2*p)/range).toFixed(1)}`).join(' '),perf=(values.at(-1)/values[0]-1)*100;return`<div class="price-chart"><div class="chart-head"><span>Storico mensile reale · ultimi ${hist.length} mesi disponibili</span><strong>${perf>=0?'+':''}${f(perf)}%</strong></div><svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><polyline points="${pts}" class="chart-line"/></svg><div class="chart-foot"><span>${hist[0].date.slice(0,7)}</span><span>Min ${f(min,2)} · Max ${f(max,2)}</span><span>${hist.at(-1).date.slice(0,7)}</span></div></div>`}
function card(i,budget,count){const per=budget/count,weight=100/count,status=i.status||'YELLOW',q=quoteInfo(i);return`<article class="etf-card selected-card" data-ticker="${i.ticker}" tabindex="0"><div class="selected-ribbon">SCELTO PER IL PAC · ${f(weight,0)}% · ${euro(per)}/mese</div><div class="etf-head"><div><small>${i.category||'ETF'} · ${role(i)}</small><h3>${i.name}</h3><span><b>${i.ticker}</b> · ${i.isin||''}</span></div><strong>${f(i.score)}/10</strong></div><div class="metrics"><div><span>Prezzo attuale</span><strong>${q.display}</strong></div><div><span>Mercato</span><strong>${q.exchange}</strong></div><div><span>Aggiornato</span><strong>${updatedLabel()}</strong></div></div><p><span class="badge ${status}">${i.verdict||'SELEZIONATO'}</span></p>${chart(i)}<div class="metrics"><div><span>TER</span><strong>${f(i.ter,2)}%</strong></div><div><span>1 anno</span><strong>${f(i.return1y)}%</strong></div><div><span>3 anni ann.</span><strong>${f(i.return3y)}%</strong></div><div><span>5 anni ann.</span><strong>${f(i.return5y)}%</strong></div><div><span>10 anni ann.</span><strong>${f(i.return10y)}%</strong></div><div><span>Max drawdown</span><strong>${f(i.drawdown)}%</strong></div></div><div class="explain"><strong>Perché è nel portafoglio</strong><p>${why(i)}</p></div><div class="open-detail">Apri scheda completa →</div></article>`}

function openDetail(i){const d=$('#etfDialog'),c=$('#etfDialogContent'),q=quoteInfo(i);c.innerHTML=`<div class="detail-hero"><small>${i.category||'ETF'} · ${role(i)}</small><h2>${i.name}</h2><p><b>${i.ticker}</b> · ${i.isin||'ISIN n.d.'}</p></div><div class="detail-metrics"><div><span>Prezzo attuale</span><b>${q.display}</b></div><div><span>Mercato</span><b>${q.exchange}</b></div><div><span>Ultimo aggiornamento</span><b>${updatedLabel()}</b></div></div><p class="detail-note">Il prezzo è quello della quotazione usata dal motore (${q.exchange}). Su Trade Republic o su un’altra Borsa lo stesso ISIN può avere valuta o prezzo numerico diversi: per il confronto verifica sempre ISIN, mercato e valuta.</p><div class="detail-grid"><section><h3>Che cos’è</h3><p>${why(i)}</p></section><section><h3>Cosa contiene</h3><p>${containsText(i)}</p></section><section><h3>Come funziona</h3><p>${structureText(i)}</p></section><section><h3>Garanzie e protezioni</h3><p>${protectionText(i)}</p></section><section><h3>Rischi principali</h3><p>${riskText(i)}</p></section><section><h3>Costi e struttura</h3><p>TER indicato: <b>${f(i.ter,2)}%</b>. Replica: <b>${i.replication||'n.d.'}</b>. Proventi: <b>${i.distribution||'n.d.'}</b>. Il TER non comprende necessariamente tutti i costi di negoziazione, spread e fiscalità.</p></section></div><div class="detail-metrics"><div><span>1 anno</span><b>${f(i.return1y)}%</b></div><div><span>3 anni ann.</span><b>${f(i.return3y)}%</b></div><div><span>5 anni ann.</span><b>${f(i.return5y)}%</b></div><div><span>10 anni ann.</span><b>${f(i.return10y)}%</b></div><div><span>Max drawdown</span><b>${f(i.drawdown)}%</b></div></div><p class="detail-note">La composizione reale e le prime partecipazioni cambiano nel tempo. Prima di acquistare conviene sempre controllare KID, factsheet e composizione aggiornata dell’emittente.</p>`;d.showModal()}

function commonMonthlyDates(etfs,years){const cut=new Date();cut.setFullYear(cut.getFullYear()-years);const maps=etfs.map(i=>new Map((i.monthlyHistory||[]).filter(x=>new Date(x.date)>=cut&&Number(x.price)>0).map(x=>[x.date,Number(x.price)])));if(!maps.length)return{dates:[],maps:[]};return{dates:[...maps[0].keys()].filter(d=>maps.every(m=>m.has(d))).sort(),maps}}
function simulateReal(monthly,years,etfs){const per=monthly/etfs.length,{dates,maps}=commonMonthlyDates(etfs,years);let value=0;const details=etfs.map((i,idx)=>{let shares=0;dates.forEach(d=>shares+=per/maps[idx].get(d));const invested=per*dates.length,current=Number(i.currentPrice)||maps[idx].get(dates.at(-1))||0,val=shares*current;value+=val;return{i,invested,val,months:dates.length}});return{total:monthly*dates.length,value,details,months:dates.length}}
function renderBuilder(){const budget=Math.max(25,Number($('#monthlyBudget').value)||250),years=Number($('#years').value)||5,picks=pick5(DATASET),per=budget/picks.length,weight=100/picks.length;$('#portfolioPlan').innerHTML=picks.map((i,n)=>{const q=quoteInfo(i);return`<div class="plan-row"><span><b>${n+1}. ${i.name}</b><small><strong>${i.ticker}</strong> · ${i.isin||'ISIN n.d.'} · ${role(i)}</small><small>Prezzo: <strong>${q.display}</strong> · ${q.exchange}</small><small>${why(i)}</small></span><div class="allocation"><strong>${euro(per)}/mese</strong><small>${f(weight,0)}% del PAC</small></div></div>`}).join('');const s=simulateReal(budget,years,picks),gain=s.value-s.total,pct=s.total?gain/s.total*100:0,requested=years*12,coverage=s.months<requested?`<div class="history-warning"><strong>Storico comune disponibile: ${s.months} rate mensili.</strong> Il calcolo usa solo i mesi presenti per tutti i 5 strumenti.</div>`:'';$('#pacSimulation').innerHTML=`<div class="sim-title"><small>SIMULAZIONE SU ACQUISTI MENSILI REALI</small><h3>Come sarebbe andato questo PAC</h3><p>Ogni mese ${euro(budget)} vengono divisi tra i 5 strumenti selezionati.</p></div>${coverage}<div class="sim-grid"><div><span>Rata mensile</span><strong>${euro(budget)}</strong></div><div><span>Rate confrontabili</span><strong>${s.months}</strong></div><div><span>Totale versato</span><strong>${euro(s.total)}</strong></div><div><span>Valore oggi</span><strong>${euro(s.value)}</strong></div><div><span>Guadagno / perdita</span><strong>${gain>=0?'+':''}${euro(gain)} · ${pct>=0?'+':''}${f(pct)}%</strong></div></div>`;$('#cards').innerHTML=picks.map(i=>card(i,budget,picks.length)).join('')}
fetch(DATA+'?v='+Date.now()).then(r=>r.json()).then(d=>{DATASET=d.etfs||[];GENERATED_AT=d.generatedAt||null;const picks=pick5(DATASET);$('#summary').innerHTML=`<div class="summary-card"><small>ETF ANALIZZATI DAL MOTORE</small><strong>${d.screenedCount||DATASET.length}</strong></div><div class="summary-card"><small>SCELTI PER IL PAC</small><strong>${picks.length}</strong></div><div class="summary-card"><small>LOGICA</small><strong>CRESCITA + ORO</strong></div>`;renderBuilder();$('#monthlyBudget').addEventListener('input',renderBuilder);$('#years').addEventListener('change',renderBuilder);$('#cards').addEventListener('click',e=>{const card=e.target.closest('.etf-card');if(card)openDetail(DATASET.find(x=>x.ticker===card.dataset.ticker))});$('#cards').addEventListener('keydown',e=>{if(e.key==='Enter'){const card=e.target.closest('.etf-card');if(card)openDetail(DATASET.find(x=>x.ticker===card.dataset.ticker))}});$('#closeEtfDialog').addEventListener('click',()=>$('#etfDialog').close());$('#etfDialog').addEventListener('click',e=>{if(e.target===$('#etfDialog'))$('#etfDialog').close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#etfDialog')?.open)$('#etfDialog').close()})});